apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-status-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-status-api
  template:
    metadata:
      labels:
        app: platform-status-api
    spec:
      containers:
        - name: api
          image: platform-status-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
